//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Search_Engine
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class web_crawlerEntities : DbContext
    {
        public web_crawlerEntities()
            : base("name=web_crawlerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Crawler> Crawlers { get; set; }
        public virtual DbSet<dic> dics { get; set; }
        public virtual DbSet<Dictionry> Dictionries { get; set; }
        public virtual DbSet<Inverted_index> Inverted_index { get; set; }
        public virtual DbSet<kgram_index> kgram_index { get; set; }
        public virtual DbSet<Soundex_Index> Soundex_Index { get; set; }
        public virtual DbSet<x> x { get; set; }
        public virtual DbSet<y> y { get; set; }
    }
}
